"""extend password field length

Revision ID: 76da30622f3e
Revises: f92b7f9473ba
Create Date: 2025-08-19 17:43:47.071925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76da30622f3e'
down_revision = 'f92b7f9473ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=300),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
